# Newest ubuntu
os: linux
dist: focal
language: node_js
node_js:
  - "lts/*" # Latest LTS Node.js version
jobs:
  include:
    - stage: "tests"
    - script: npm test
      name: "npm test"

    # mochawesome is allowed to fail, as it only generates the report
    - script: npm test -- --reporter mochawesome || true
      name: "mochaawesome report"
      # Deploy mochawesome HTML to github pages
      deploy:
        provider: pages:git
        token: $GITHUB_TOKEN
        local_dir: mochawesome-report
        edge: true
