# Latest ubuntu
os: linux
dist: focal
language: node_js
node_js:
  - "lts/*" # Latest LTS Node.js version
env:
  global:
    - COVERALLS_PARALLEL=true
jobs:
  include:
    - stage: "tests"
    - script: npm test
      name: "npm test"

    # tests are ok to fail as this only generates the html report
    - script: npm test -- --reporter mochawesome || true
      name: "mochaawesome report"
      env:
        # github-pages only recognizes index.html
        - MOCHAWESOME_REPORTFILENAME=index.html
      # Deploy mochawesome HTML to the repo's github pages
      deploy:
        provider: pages:git
        token: $GITHUB_TOKEN
        local_dir: mochawesome-report # only the contents of mochwesome
        edge: true
        on:
          branch: main # default is still "master" with travis CI :(

    # c8 generates the lcov coverage files, which coveralls script passes to
    # coveralls.io
    - script:
      # Failing tests should not fail coverage
      - npm run c8 -- --reporter=lcovonly mocha || true
      - npm run coveralls -- -v < coverage/lcov.info
      name: "coveralls"
      notifications:
        webhooks: https://coveralls.io/webhook
