# Latest ubuntu
os: linux
dist: focal
language: node_js
node_js:
  - "lts/*" # Latest LTS Node.js version
env:
  global:
    - COVERALLS_PARALLEL=true
jobs:
  include:
    - name: "mochaawesome report"
      env:
        # github-pages only recognizes index.html
        - MOCHAWESOME_REPORTFILENAME=index.html

      after_install:
        npm install --no-save mochawesome

      # tests are ok to fail as this only generates the html report
      script: npm test -- --reporter mochawesome || true

      # Deploy mochawesome HTML to the repo's github pages
      deploy:
        provider: pages:git
        token: $GITHUB_TOKEN
        local_dir: mochawesome-report # only the contents of mochawesome
        edge: true
        on:
          branch: main # default is still "master" with travis CI :(

    # c8 generates the lcov coverage files, which coveralls script passes to
    # coveralls.io
    - name: "coveralls"
      after_install:
        npm install --no-save coveralls

      script:
      # Failing tests should not fail coverage
      - ./node_modules/.bin/c8 --reporter=lcovonly mocha || true
      - ./node_modules/.bin/coveralls -v < coverage/lcov.info

      notifications:
        webhooks: https://coveralls.io/webhook
