# Newest ubuntu
os: linux
dist: focal
language: node_js
node_js:
  - "lts/*" # Latest LTS Node.js version
env:
  global:
    - COVERALLS_PARALLEL=true
jobs:
  include:
    - stage: "tests"
    - script: npm test
      name: "npm test"

    # mochawesome is allowed to fail, as it only generates the report
    - script: npm test -- --reporter mochawesome || true
      name: "mochaawesome report"
      env:
        # github pages only recognizes index.html
        - MOCHAWESOME_REPORTFILENAME=index.html
      # Deploy mochawesome HTML to github pages
      deploy:
        provider: pages:git
        token: $GITHUB_TOKEN
        local_dir: mochawesome-report
        edge: true
        on:
          branch: main # default is still "master" with travis CI :D

      - script:
        - npm c8 -- --reporter=lcovonly mocha || true
        - npm run coveralls -- < coverage/lcov.info
        name: "coveralls"
        notifications:
          webhooks: https://coveralls.io/webhook
